// This file is auto-generated by @hey-api/openapi-ts

export type WeatherForecast = {
    date?: string;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: (string) | null;
};

export type GetWeatherForecastResponse = (Array<WeatherForecast>);